const express = require("express");
const router = express.Router();
const c = require("../controllers/subjectScoreController");
const protect = require("../middleware/authMiddleware");
const authorize = require("../middleware/roleMiddleware");
router.get("/subjects", protect, authorize("admin"), c.getSubjects);
router.post("/subjects", protect, authorize("admin"), c.createSubject);
router.get("/level-curriculum", protect, authorize("admin"), c.getLevelCurriculum);
router.post("/level-curriculum", protect, authorize("admin"), c.createLevelCurriculum);
router.post("/level-curriculum/apply/:classId", protect, authorize("admin"), c.applyLevelCurriculum);
router.get("/class-subjects", protect, authorize("admin"), c.getClassSubjects);
router.post("/class-subjects", protect, authorize("admin"), c.createClassSubject);
router.post("/class-subjects/batch", protect, authorize("admin"), c.createClassSubjectsBatch);
router.put("/class-subjects/assign-teacher", protect, authorize("admin"), c.assignTeacherToSubjects);
router.put("/class-subjects/:id", protect, authorize("admin"), c.updateClassSubject);
router.get("/teacher/books", protect, authorize("teacher"), c.getTeacherScoreBooks);
router.get("/teacher/class-scoresheet", protect, authorize("teacher"), c.getClassScoreSheet);
router.get("/teacher/class-scoresheet/print", protect, authorize("teacher"), c.getPrintableClassScoreSheet);
router.get("/book", protect, authorize("admin", "teacher"), c.getScoreBook);
router.put("/book", protect, authorize("admin", "teacher"), c.saveScoreBook);
router.put("/book/lock", protect, authorize("admin"), c.lockScoreBook);
module.exports = router;
