const Class = require("../models/classModel");
const Student = require("../models/studentModel");
const Teacher = require("../models/teacherModel");
const ClassSubject = require("../models/classSubjectModel");
const StudentSubjectScore = require("../models/studentSubjectScoreModel");
const Subject = require("../models/subjectModel");
const TeachingAssignment = require("../models/teachingAssignmentModel");
const LevelCurriculum = require("../models/levelCurriculumModel");

const terms = ["First Term", "Second Term", "Third Term"];
const activeStudents = { $or: [{ status: "active" }, { status: { $exists: false } }, { status: null }, { status: "" }] };
const scoreTotal = (row) => Number(row.first_ca || 0) + Number(row.second_ca || 0) + Number(row.exam || 0);
const validScore = (value, max) => Number.isFinite(Number(value)) && Number(value) >= 0 && Number(value) <= max;
const getPolicy = (subject = {}) => ({ first_ca_max: subject.assessment_policy?.first_ca_max ?? 20, second_ca_max: subject.assessment_policy?.second_ca_max ?? 20, exam_max: subject.assessment_policy?.exam_max ?? 60 });
const getActiveAssignment = (classSubjectId) => TeachingAssignment.findOne({ class_subject: classSubjectId, role: "primary", status: "active" });
const canTeacherAccess = async (subject, teacherId) => {
  const assignment = await getActiveAssignment(subject._id);
  if (assignment) return { allowed: assignment.teacher.toString() === teacherId.toString(), assignment };
  // Existing installations used this direct field before assignment history was introduced.
  return { allowed: subject.assigned_teacher?.toString() === teacherId.toString(), assignment: null };
};
const getFormTeacherClassScoreSheet = async (teacherId, term) => {
  const teacher = await Teacher.findById(teacherId).populate("assigned_class_record", "name session section");
  if (!teacher || teacher.status !== "active") throw Object.assign(new Error("Active teacher account not found"), { status: 403 });
  if (teacher.assignment_type !== "form_teacher" || !teacher.assigned_class_record) throw Object.assign(new Error("Class scoresheets are available to assigned form teachers only"), { status: 403 });
  const classRecord = teacher.assigned_class_record;
  const offerings = await ClassSubject.find({ class_record: classRecord._id, session: classRecord.session, status: "active" }).populate("subject_record", "name code").sort({ subject: 1 }).lean();
  const students = await Student.find({ $and: [activeStudents, { class_record: classRecord._id, current_session: classRecord.session }] }).select("full_name admission_no").sort({ full_name: 1 }).lean();
  const scores = await StudentSubjectScore.find({ class_subject: { $in: offerings.map((item) => item._id) }, session: classRecord.session, term }).lean();
  const byKey = new Map(scores.map((score) => [`${score.student}:${score.class_subject}`, score]));
  const incomplete = [];
  const rows = students.map((student) => ({ ...student, subjects: offerings.map((offering) => { const score = byKey.get(`${student._id}:${offering._id}`) || null; const final = ["submitted", "locked"].includes(score?.status); if (!final) incomplete.push({ student: student.full_name, subject: offering.subject_record?.name || offering.subject, status: score?.status || "missing" }); return { class_subject: offering._id, subject: offering.subject_record?.name || offering.subject, total: score?.total ?? null, status: score?.status || "missing" }; }) }));
  return { class_record: classRecord, teacher: { full_name: teacher.full_name }, term, subjects: offerings.map((item) => ({ _id: item._id, name: item.subject_record?.name || item.subject })), students: rows, complete: Boolean(offerings.length && students.length && incomplete.length === 0), incomplete, message: !offerings.length ? "No active subjects are registered for this class" : !students.length ? "No active students are registered for this class" : incomplete.length ? `${incomplete.length} score entry or submission(s) still need attention` : "All subject scores are submitted or locked" };
};

const getSubjects = async (req, res) => { try { res.json(await Subject.find({ status: "active" }).sort({ name: 1 })); } catch (e) { res.status(500).json({ message: e.message }); } };
const createSubject = async (req, res) => { try { const name = req.body.name?.trim(); if (!name) return res.status(400).json({ message: "Subject name is required" }); const subject = await Subject.create({ name, code: req.body.code?.trim() || "" }); res.status(201).json(subject); } catch (e) { res.status(e.code === 11000 ? 400 : 500).json({ message: e.code === 11000 ? "A subject with this name or code already exists" : e.message }); } };
const sections = ["pre_nursery", "nursery", "basic", "secondary"];
const parsePolicy = (policy = {}) => { const result = { first_ca_max: Number(policy.first_ca_max ?? 20), second_ca_max: Number(policy.second_ca_max ?? 20), exam_max: Number(policy.exam_max ?? 60) }; return Object.values(result).some((value) => !Number.isFinite(value) || value < 0) || result.first_ca_max + result.second_ca_max + result.exam_max !== 100 ? null : result; };
const getLevelCurriculum = async (req, res) => { try { const query = { status: "active" }; if (req.query.section) query.section = req.query.section; res.json(await LevelCurriculum.find(query).populate("subject_record", "name code").sort({ section: 1, createdAt: 1 })); } catch (e) { res.status(500).json({ message: e.message }); } };
const createLevelCurriculum = async (req, res) => { try { const { section, subject_id, assessment_policy } = req.body; if (!sections.includes(section)) return res.status(400).json({ message: "Select a valid academic level" }); const subject = await Subject.findOne({ _id: subject_id, status: "active" }); const policy = parsePolicy(assessment_policy); if (!subject) return res.status(400).json({ message: "Select an active catalogue subject" }); if (!policy) return res.status(400).json({ message: "Assessment components must be non-negative and total 100" }); const item = await LevelCurriculum.create({ section, subject_record: subject._id, assessment_policy: policy }); res.status(201).json(await item.populate("subject_record", "name code")); } catch (e) { res.status(e.code === 11000 ? 400 : 500).json({ message: e.code === 11000 ? "This subject is already in the selected level curriculum" : e.message }); } };
const applyLevelCurriculum = async (req, res) => { try { const classRecord = await Class.findById(req.params.classId); if (!classRecord) return res.status(404).json({ message: "Class not found" }); if (!classRecord.section) return res.status(400).json({ message: "This class must have an academic level before a curriculum can be applied" }); const curriculum = await LevelCurriculum.find({ section: classRecord.section, status: "active" }).populate("subject_record", "name"); if (!curriculum.length) return res.status(400).json({ message: "No active curriculum subjects are registered for this academic level" }); const existing = await ClassSubject.find({ class_record: classRecord._id }).select("subject_record subject").lean(); const knownSubjectIds = new Set(existing.map((item) => item.subject_record?.toString()).filter(Boolean)); const knownNames = new Set(existing.map((item) => item.subject.toLowerCase())); const missing = curriculum.filter((item) => !knownSubjectIds.has(item.subject_record._id.toString()) && !knownNames.has(item.subject_record.name.toLowerCase())); if (missing.length) await ClassSubject.insertMany(missing.map((item) => ({ class_record: classRecord._id, session: classRecord.session, subject_record: item.subject_record._id, subject: item.subject_record.name, assessment_policy: item.assessment_policy })));
  res.json({ message: `${missing.length} curriculum subject(s) added to ${classRecord.name.toUpperCase()}`, added: missing.length, already_present: curriculum.length - missing.length });
} catch (e) { res.status(500).json({ message: e.message }); } };

const getClassSubjects = async (req, res) => { try { const query = {}; if (req.query.class_record) query.class_record = req.query.class_record; if (req.query.session) query.session = req.query.session; const rows = await ClassSubject.find(query).populate("class_record", "name session").populate("subject_record", "name code").populate("assigned_teacher", "full_name username status").sort({ session: -1, subject: 1 }).lean(); const assignments = await TeachingAssignment.find({ class_subject: { $in: rows.map((row) => row._id) }, status: "active", role: "primary" }).populate("teacher", "full_name username status").lean(); const assignmentByOffering = new Map(assignments.map((item) => [item.class_subject.toString(), item])); res.json(rows.map((row) => ({ ...row, active_assignment: assignmentByOffering.get(row._id.toString()) || null }))); } catch (e) { res.status(500).json({ message: e.message }); } };
const createClassSubject = async (req, res) => { try { const { class_record, subject_id, assessment_policy = {} } = req.body; const classRecord = await Class.findById(class_record); const subjectRecord = await Subject.findOne({ _id: subject_id, status: "active" }); if (!classRecord || !subjectRecord) return res.status(400).json({ message: "Select an existing class and active catalogue subject" }); const policy = { first_ca_max: Number(assessment_policy.first_ca_max ?? 20), second_ca_max: Number(assessment_policy.second_ca_max ?? 20), exam_max: Number(assessment_policy.exam_max ?? 60) }; if (Object.values(policy).some((value) => !Number.isFinite(value) || value < 0) || policy.first_ca_max + policy.second_ca_max + policy.exam_max !== 100) return res.status(400).json({ message: "Assessment components must be non-negative and total 100" }); const item = await ClassSubject.create({ class_record: classRecord._id, session: classRecord.session, subject_record: subjectRecord._id, subject: subjectRecord.name, assessment_policy: policy }); res.status(201).json(await item.populate(["class_record", "subject_record"])); } catch (e) { res.status(e.code === 11000 ? 400 : 500).json({ message: e.code === 11000 ? "This subject is already offered by the class" : e.message }); } };
const createClassSubjectsBatch = async (req, res) => { try { const { class_record, subject_ids = [], assessment_policy } = req.body; if (!Array.isArray(subject_ids) || !subject_ids.length) return res.status(400).json({ message: "Select at least one catalogue subject" }); const classRecord = await Class.findById(class_record); const uniqueIds = [...new Set(subject_ids.map((id) => id?.toString()).filter(Boolean))]; const subjects = await Subject.find({ _id: { $in: uniqueIds }, status: "active" }); const policy = parsePolicy(assessment_policy); if (!classRecord || subjects.length !== uniqueIds.length) return res.status(400).json({ message: "Select an existing class and active catalogue subjects" }); if (!policy) return res.status(400).json({ message: "Assessment components must be non-negative and total 100" }); const existing = await ClassSubject.find({ class_record: classRecord._id }).select("subject_record subject").lean(); const subjectIds = new Set(existing.map((item) => item.subject_record?.toString()).filter(Boolean)); const subjectNames = new Set(existing.map((item) => item.subject.toLowerCase())); const missing = subjects.filter((subject) => !subjectIds.has(subject._id.toString()) && !subjectNames.has(subject.name.toLowerCase())); if (missing.length) await ClassSubject.insertMany(missing.map((subject) => ({ class_record: classRecord._id, session: classRecord.session, subject_record: subject._id, subject: subject.name, assessment_policy: policy })));
  res.status(201).json({ message: `${missing.length} class-specific subject(s) added`, added: missing.length, skipped: subjects.length - missing.length });
} catch (e) { res.status(e.code === 11000 ? 409 : 500).json({ message: e.code === 11000 ? "One or more subjects were added concurrently. Refresh and try again." : e.message }); } };
const updateClassSubject = async (req, res) => { try { const { status, assessment_policy } = req.body; const changes = {}; if (status) changes.status = status; if (assessment_policy) { const policy = { first_ca_max: Number(assessment_policy.first_ca_max), second_ca_max: Number(assessment_policy.second_ca_max), exam_max: Number(assessment_policy.exam_max) }; if (Object.values(policy).some((value) => !Number.isFinite(value) || value < 0) || policy.first_ca_max + policy.second_ca_max + policy.exam_max !== 100) return res.status(400).json({ message: "Assessment components must be non-negative and total 100" }); changes.assessment_policy = policy; } const item = await ClassSubject.findByIdAndUpdate(req.params.id, changes, { new: true }).populate(["class_record", "subject_record"]); if (!item) return res.status(404).json({ message: "Class subject not found" }); res.json(item); } catch (e) { res.status(500).json({ message: e.message }); } };
const assignTeacherToSubjects = async (req, res) => { try { const { teacher_id, class_subject_ids = [], reason = "Batch assignment" } = req.body; const teacher = await Teacher.findOne({ _id: teacher_id, status: "active" }); const offerings = await ClassSubject.find({ _id: { $in: class_subject_ids }, status: "active" }); if (!teacher || !Array.isArray(class_subject_ids) || !class_subject_ids.length || offerings.length !== class_subject_ids.length) return res.status(400).json({ message: "An active teacher and valid registered class subjects are required" }); const now = new Date(); await TeachingAssignment.updateMany({ class_subject: { $in: class_subject_ids }, role: "primary", status: "active" }, { status: "ended", ends_at: now, ended_by: req.user.id, change_reason: reason }); await TeachingAssignment.insertMany(offerings.map((offering) => ({ class_subject: offering._id, teacher: teacher._id, session: offering.session, assigned_by: req.user.id, change_reason: reason }))); await ClassSubject.updateMany({ _id: { $in: class_subject_ids } }, { assigned_teacher: teacher._id }); res.json({ message: `${offerings.length} teaching assignment(s) saved with history` }); } catch (e) { res.status(e.code === 11000 ? 409 : 500).json({ message: e.code === 11000 ? "A subject was reassigned concurrently. Refresh and try again." : e.message }); } };
const getTeacherScoreBooks = async (req, res) => { try { const assignments = await TeachingAssignment.find({ teacher: req.user.id, status: "active", role: "primary" }); const ids = assignments.map((item) => item.class_subject); const rows = await ClassSubject.find({ status: "active", $or: [{ _id: { $in: ids } }, { assigned_teacher: req.user.id }] }).populate("class_record", "name session").populate("subject_record", "name code").sort({ session: -1, subject: 1 }); res.json(rows); } catch (e) { res.status(500).json({ message: e.message }); } };
const getClassScoreSheet = async (req, res) => { try { const term = req.query.term || "First Term"; if (!terms.includes(term)) return res.status(400).json({ message: "Select a valid term" }); res.json(await getFormTeacherClassScoreSheet(req.user.id, term)); } catch (e) { res.status(e.status || 500).json({ message: e.message }); } };
const getPrintableClassScoreSheet = async (req, res) => { try { const term = req.query.term || "First Term"; if (!terms.includes(term)) return res.status(400).json({ message: "Select a valid term" }); const sheet = await getFormTeacherClassScoreSheet(req.user.id, term); if (!sheet.complete) return res.status(409).json({ message: `Broadsheet printing is blocked: ${sheet.message}`, incomplete: sheet.incomplete }); res.json(sheet); } catch (e) { res.status(e.status || 500).json({ message: e.message }); } };
const getScoreBook = async (req, res) => { try { const { class_subject, term } = req.query; if (!class_subject || !terms.includes(term)) return res.status(400).json({ message: "Class subject and valid term are required" }); const subject = await ClassSubject.findById(class_subject).populate("class_record", "name session").populate("subject_record", "name code"); if (!subject) return res.status(404).json({ message: "Class subject not found" }); const access = req.user.role === "teacher" ? await canTeacherAccess(subject, req.user.id) : { allowed: true, assignment: null }; if (!access.allowed) return res.status(403).json({ message: "This score book is not assigned to you" }); const students = await Student.find({ $and: [activeStudents, { class_record: subject.class_record._id, current_session: subject.session }] }).select("full_name admission_no").sort({ full_name: 1 }).lean(); const scores = await StudentSubjectScore.find({ class_subject, session: subject.session, term }).lean(); const byStudent = new Map(scores.map((score) => [score.student.toString(), score])); res.json({ subject, assignment: access.assignment, term, students: students.map((student) => ({ ...student, score: byStudent.get(student._id.toString()) || null })) }); } catch (e) { res.status(500).json({ message: e.message }); } };
const saveScoreBook = async (req, res) => { try { const { class_subject, term, scores = [], submit = false } = req.body; if (!class_subject || !terms.includes(term) || !Array.isArray(scores)) return res.status(400).json({ message: "Class subject, term, and scores are required" }); const subject = await ClassSubject.findById(class_subject); if (!subject || subject.status !== "active") return res.status(404).json({ message: "Active class subject not found" }); const access = req.user.role === "teacher" ? await canTeacherAccess(subject, req.user.id) : { allowed: true, assignment: null }; if (!access.allowed) return res.status(403).json({ message: "This score book is not assigned to you" }); const students = await Student.find({ _id: { $in: scores.map((row) => row.student) }, class_record: subject.class_record, current_session: subject.session }).select("_id").lean(); if (students.length !== scores.length) return res.status(400).json({ message: "One or more students do not belong to this class" }); const policy = getPolicy(subject); for (const row of scores) { if (!validScore(row.first_ca, policy.first_ca_max) || !validScore(row.second_ca, policy.second_ca_max) || !validScore(row.exam, policy.exam_max)) return res.status(400).json({ message: `Scores must be within CA1 0-${policy.first_ca_max}, CA2 0-${policy.second_ca_max}, and exam 0-${policy.exam_max}` }); const existing = await StudentSubjectScore.findOne({ student: row.student, class_subject, session: subject.session, term }); if (existing?.status === "locked") return res.status(403).json({ message: "Locked scores cannot be changed" }); await StudentSubjectScore.findOneAndUpdate({ student: row.student, class_subject, session: subject.session, term }, { first_ca: Number(row.first_ca), second_ca: Number(row.second_ca), exam: Number(row.exam), total: scoreTotal(row), status: submit ? "submitted" : "draft", entered_by: req.user.id, teaching_assignment: access.assignment?._id || null, submitted_at: submit ? new Date() : null }, { upsert: true, new: true, setDefaultsOnInsert: true }); } res.json({ message: submit ? "Scores submitted for review" : "Scores saved as draft" }); } catch (e) { res.status(500).json({ message: e.message }); } };
const lockScoreBook = async (req, res) => { try { const { class_subject, term, locked } = req.body; if (!class_subject || !terms.includes(term)) return res.status(400).json({ message: "Class subject and term are required" }); const subject = await ClassSubject.findById(class_subject); if (!subject) return res.status(404).json({ message: "Class subject not found" }); await StudentSubjectScore.updateMany({ class_subject, session: subject.session, term }, locked ? { status: "locked", locked_by: req.user.id, locked_at: new Date() } : { status: "draft", locked_by: null, locked_at: null }); res.json({ message: locked ? "Score book locked" : "Score book reopened" }); } catch (e) { res.status(500).json({ message: e.message }); } };
module.exports = { getSubjects, createSubject, getLevelCurriculum, createLevelCurriculum, applyLevelCurriculum, getClassSubjects, createClassSubject, createClassSubjectsBatch, updateClassSubject, assignTeacherToSubjects, getTeacherScoreBooks, getClassScoreSheet, getPrintableClassScoreSheet, getScoreBook, saveScoreBook, lockScoreBook };
